#todo change name
name: yitam.dev
services:
  db:
    image: postgres:latest
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
